=== shahkrishna1295/SupportTicketSystem/users.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="users">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="user" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="logininfo">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="credential">
                      <xs:complexType>
                        <xs:attribute type="xs:string" name="username" use="required"/>
                        <xs:attribute type="pass" name="password" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="userinfo">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="firstname"/>
                          <xs:element type="xs:string" name="lastname"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="phonepat" name="phoneno"/>
                    <xs:element type="emailadd" name="email"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              
            </xs:sequence>
            <xs:attribute type="xs:string" name="id" use="required"/>
            <xs:attribute type="types" name="type" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:simpleType name="pass">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z]\w{3,14}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="phonepat">
    <xs:restriction base="xs:integer">
      <xs:pattern value="[0-9]{10}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="emailadd">
    <xs:restriction base="xs:string">
      <xs:pattern value="[^@]+@[^\.]+\..+"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="types">
    <xs:restriction base="xs:string">
      <xs:enumeration value="client" />
      <xs:enumeration value="staff" />
      <xs:enumeration value="admin" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== shahkrishna1295/SupportTicketSystem/xml/users.xml
<?xml version="1.0" encoding="utf-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="users.xsd">
  <user id="111" type="staff">
    <logininfo>
	  <username>admin</username>
	  <password>Ad001</password>
    </logininfo>
    <userinfo>
      <name>
        <firstname>Krishna</firstname>
        <lastname>Shah</lastname>
      </name>
      <phoneno>8005555555</phoneno>
      <email>admin@gmail.com</email>
    </userinfo>
  </user>
  <user id="222" type="staff">
    <logininfo>
      <username>staff</username>
	  <password>S001</password>
    </logininfo>
    <userinfo>
      <name>
        <firstname>Support</firstname>
        <lastname>Staff</lastname>
      </name>
      <phoneno>9876543210</phoneno>
      <email>staff@gmail.com</email>
    </userinfo>
  </user>
  <user id="333" type="client">
    <logininfo>
      <username>Client</username>
	  <password>C001</password>
    </logininfo>
    <userinfo>
      <name>
        <firstname>Client</firstname>
        <lastname>One</lastname>
      </name>
      <phoneno>6789054321</phoneno>
      <email>client@gmail.com</email>
    </userinfo>
  </user>
  <user id="444" type="client">
    <logininfo>
      <username>Vicky</username>
	  <password>Kaushal</password>
    </logininfo>
    <userinfo>
      <name>
        <firstname>Client</firstname>
        <lastname>TWO</lastname>
      </name>
      <phoneno>6789054321</phoneno>
      <email>client@gmail.com</email>
    </userinfo>
  </user>
</users>
